name: Deploy to Encore Cloud

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Install Encore CLI
        run: |
          curl -L https://encore.dev/install.sh | bash
          export PATH=$PATH:$HOME/.encore/bin
          encore version

      - name: Authenticate with Encore
        run: encore auth login --ci --token ${{ secrets.ENCORE_AUTH_TOKEN }}

      - name: Deploy to Encore Cloud
        run: encore app deploy --prod

      - name: Seed Database (only on first deploy or when requested)
        if: ${{ github.event_name == 'workflow_dispatch' }} 
        run: |
          # Get the API URL from Encore
          API_URL=$(encore app url --prod)
          # Call the seed API endpoint
          curl -X POST $API_URL/api/seed