name: Deploy to Encore Cloud

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      # Sử dụng Encore GitHub Action chính thức
      - name: Deploy to Encore
        uses: encoredev/github-action@v1
        with:
          auth_token: ${{ secrets.ENCORE_AUTH_TOKEN }}
          command: deploy --production

      # Seed database nếu cần thiết (chỉ khi chạy thủ công)
      - name: Seed Database (manual trigger only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: encoredev/github-action@v1
        with:
          auth_token: ${{ secrets.ENCORE_AUTH_TOKEN }}
          command: run -e production -- curl -X POST $(encore app url --production)/api/seed