name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Type check
        run: npx tsc --noEmit || echo "Type checking skipped"
      
      - name: List test files
        run: find . -name "*.test.ts" -type f || echo "No test files found"
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Configure Encore auth manually
        run: |
          # Tạo thư mục cấu hình Encore
          mkdir -p $HOME/.encore
          
          # Tạo file cấu hình cho Encore CLI với token
          echo '{
            "auth_token": "${{ secrets.ENCORE_AUTH_TOKEN }}"
          }' > $HOME/.encore/config.json
          
          # Hiển thị nội dung file config (ẩn token)
          echo "Đã tạo file cấu hình Encore:"
          cat $HOME/.encore/config.json | sed 's/"auth_token": ".*"/"auth_token": "***"/g'
      
      - name: Deploy to Encore Cloud using Git Integration
        run: |
          # Hiển thị phiên bản Encore
          $HOME/.encore/bin/encore version
          
          # Cấu hình Git remote cho Encore
          echo "Cấu hình Git remote cho Encore..."
          git remote remove encore || true
          git remote add encore "encore://backend-xbk2.git"
          
          # Hiển thị các remote
          echo "Danh sách remote:"
          git remote -v
          
          # Cấu hình SSH để tự động chấp nhận host key
          echo "Cấu hình SSH cho Encore..."
          mkdir -p ~/.ssh
          ssh-keyscan encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan git.encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan git.encore.cloud >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan app.encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          
          # Thiết lập SSH để tự động chấp nhận hosts mới
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Thử sử dụng ssh-agent 
          eval "$(ssh-agent -s)"
          
          # Đẩy code lên Encore
          echo "Đang triển khai lên Encore Cloud..."
          GIT_SSH_COMMAND="ssh -v" git push -f encore HEAD:refs/heads/main
          
          echo "===== Triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.dev/backend-xbk2"

      - name: Seed Database (only when manually triggered)
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Đợi một chút để đảm bảo deployment đã hoàn tất
          sleep 30
          
          # Sử dụng URL cố định vì chúng ta biết app ID
          APP_URL="https://backend-xbk2-production.encr.app"
          echo "Seeding database at: $APP_URL/api/seed"
          curl -X POST "$APP_URL/api/seed" || echo "Failed to seed database"