name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Type check
        run: npx tsc --noEmit || echo "Type checking skipped"
      
      - name: List test files
        run: find . -name "*.test.ts" -type f || echo "No test files found"
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
          chmod +x $HOME/.encore/bin/encore
          ls -la $HOME/.encore/bin/
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Deploy to Encore Cloud
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}
        run: |
          # Hiển thị phiên bản Encore
          encore version
          
          # Kiểm tra ứng dụng Encore
          echo "Checking Encore app information..."
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # Liệt kê các lệnh của Encore để debug
          echo "Available Encore commands:"
          encore help
          
          # Kiểm tra lệnh app
          echo "Checking 'app' commands:"
          encore app --help
          
          # Thực hiện triển khai trực tiếp
          echo "Triển khai trực tiếp lên Encore Cloud..."
          encore app deploy $APP_ID -e production
          
          echo "===== Triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.dev/$APP_ID"

      - name: Seed Database (only when manually triggered)
        if: github.event_name == 'workflow_dispatch'
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}
        run: |
          # Đợi một chút để đảm bảo deployment đã hoàn tất
          sleep 30
          
          # Sử dụng URL cố định vì chúng ta biết app ID
          APP_URL="https://backend-xbk2-production.encr.app"
          echo "Seeding database at: $APP_URL/api/seed"
          curl -X POST "$APP_URL/api/seed" || echo "Failed to seed database"